name:  Sample Hello world

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      message: Hello world
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: print the message
      run: "echo $env:message"
    - name: print the message local
      run: "echo $env:message"
      env:
        message: Hello world local